package com.halehan.demo.rest.controller

import com.halehan.demo.rest.model.Patient
import com.halehan.demo.rest.model.PatientRepository
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.stereotype.Controller
import org.springframework.web.bind.annotation.*

@Controller // This means that this class is a Controller
@RequestMapping(path = ["/demo"]) // This means URL's start with /demo (after Application path)
class MainController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private val patientRepository: PatientRepository? = null

    @PostMapping(path = ["/add"]) // Map ONLY POST Requests
    @ResponseBody
    fun addNewUser(@RequestBody newPatient: Patient?): Int? {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request
        println("In the add")
        val p = Patient()
        p.studyid = newPatient?.studyid
        p.firstname = newPatient?.firstname
        p.setLastName(newPatient?.lastname)
        p.email = newPatient?.email
        patientRepository!!.save(p)
        return p.id
    }

    // This returns a JSON or XML with the users
    @get:ResponseBody
    @get:GetMapping(path = ["/all"])
    val allUsers: Iterable<Patient?>
        get() =// This returns a JSON or XML with the users
            patientRepository!!.findAll()
}