package com.halehan.demo.rest.service;

import com.halehan.demo.rest.model.AppModelMapper;
import com.halehan.demo.rest.model.Patient;
import com.halehan.demo.rest.model.PatientCrudRepository;
import com.halehan.demo.rest.model.PatientDTO;
import org.modelmapper.ModelMapper;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.dao.DataAccessException;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import java.util.Comparator;
import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;

@Service
public class PatientServiceImpl implements PatientService{

    Logger logger = LoggerFactory.getLogger(PatientServiceImpl.class);

    @Autowired
    AppModelMapper dtoMapper;

    @Autowired
    // This means to get the bean called patientRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    PatientCrudRepository patientRepository;

    @Transactional(propagation = Propagation.REQUIRES_NEW )
    public String updatePatient(PatientDTO p, int id) {

        Optional<Patient> patientOptional = patientRepository.findById(id);
        String rtn = "Success";

        if (patientOptional.isEmpty())
            rtn =  "No User with id: " + id;

        try{
            patientOptional.ifPresent(patient -> {
                System.out.println("User's name = " + patient.getEmail());
                if (checkedValue(p.getEmail()))
                    patient.setEmail(p.getEmail());
                if (checkedValue(p.getFirstName()))
                    patient.setFirstname(p.getFirstName());
                if (checkedValue(p.getLastName()))
                    patient.setLastname(p.getLastName());
                if (checkedValue(p.getStatus()))
                    patient.setStatus(p.getStatus());
                if (checkedValue(p.getStudyEye()))
                    patient.setStudyeye(p.getStudyEye());

                patient.setId(Math.toIntExact(id));

                patientRepository.save(patient);
            });

        } catch (Exception ee) {
            rtn = "Failure: " + ee.getMessage();

        }

        return rtn;

    }

    public String addPatient(PatientDTO newPatient) {

        System.out.println("/add Post " + newPatient.getEmail() +"\n" + newPatient.getLastName());
        Patient p = new Patient();
        p.setStudyeye(newPatient.getStudyEye());
        p.setStatus(newPatient.getStatus());
        p.setStudyid(newPatient.getStudyId());
        p.setFirstname(newPatient.getFirstName());
        p.setLastname(newPatient.getLastName());
        p.setEmail(newPatient.getEmail());
        String rtn = "Success: ";
        try{
            patientRepository.save(p);
            rtn += "Added id " + p.getId();
        } catch (DataAccessException e) {
            rtn = "Error: " + e.getMessage();
        }
        return rtn;
    }

    @Transactional(propagation = Propagation.NOT_SUPPORTED )
    public List<PatientDTO> findByLastName(String lastName) {

        return  patientRepository.findByLastname(lastName).stream()
                .sorted(Comparator.comparing(Patient::getStudyeye).thenComparing(Patient::getLastname))
                .map(dtoMapper::mapPatientDto).collect(Collectors.toList());
    }

    @Transactional(propagation = Propagation.NOT_SUPPORTED )
    public List<PatientDTO> getAllPatients() {

      return  ((List<Patient>) patientRepository.findAll()).stream()
              .sorted(Comparator.comparing(Patient::getStudyeye).thenComparing(Patient::getLastname))
              .map(dtoMapper::mapPatientDto).collect(Collectors.toList());
    }

    public String deletePatient(int id) {
        String rtn = "success";
        try{
            patientRepository.deleteById(id);
        } catch (Exception e) {
            rtn = "Fail:  " +  e.getMessage();
        }
        return rtn;

    }

    private boolean checkedValue(String val) {
        return (val == null || val.isEmpty()) ? false : true;
    }
}
