package com.halehan.demo.rest.service;

import com.halehan.demo.rest.model.Patient;
import com.halehan.demo.rest.model.PatientCrudRepository;
import com.halehan.demo.rest.model.Procedure;
import com.halehan.demo.rest.model.ProcedureRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
public class ProcedureServiceImpl {
    @Autowired
    // This means to get the bean called patientRepository
            // Which is auto-generated by Spring, we will use it to handle the data
            ProcedureRepository procedureRepository;

    public  Iterable<Procedure>  getAllProcedures() {
        Iterable<Procedure> procedures = null;

        try {procedures = procedureRepository.findAll();}
        catch (Exception e) {
            System.out.println(e.getMessage());
        }

        return procedures;
    }
}
