package com.halehan.demo.rest.controller.mongo.ct;

import com.halehan.demo.rest.model.mongo.ct.Person;
import com.halehan.demo.rest.model.mongo.ct.PersonDto;
import com.halehan.demo.rest.service.mongo.ct.PersonService;
import org.bson.types.ObjectId;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller // This means that this class is a Controller
@RequestMapping(path="/person") // This means URL's start with /demo (after Application path)
public class PersonController {

    @Autowired
    // This means to get the bean called patientService
    // Which is auto-generated by Spring, we will use it to handle the data
    PersonService personService;

    @GetMapping("/{id}")
    public @ResponseBody
    PersonDto getById(@PathVariable ObjectId id ) {
        return  personService.findById(id);
    }

    @GetMapping(path="/lastName/{lastName}")
    public @ResponseBody
    Iterable<Person> getByLastName(@PathVariable String lastName) {
        return  personService.findByLastName(lastName);
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<Person> getAllUsers() {
        return  personService.findAll();
    }

    @DeleteMapping("/{id}")
    public @ResponseBody String deletePerson(@PathVariable ObjectId id) {
        return personService.deletePerson(id);
    }



}
